### ISSUE TITLE
open /usr/local/bin/jamf: permission denied

### ISSUE THREAD

**Issue by mastertinner** [bfirsh/whalebrew#30] opened 2017-01-30 12:04 UTC
I can install and run whalebrew commands with no problem. When I run `whalebrew list`, however, I get `open /usr/local/bin/jamf: permission denied`. I'm running macOS Sierra 10.12.2 (Darwin Kernel Version 16.3.0) and Docker for Mac 1.13.0.

**Comment by bfirsh** [comment] 2017-01-30 13:50
Thanks for the report! Dupe of #7.

**Closed by bfirsh** 2017-01-30 13:50 UTC

**Comment by mastertinner** [comment] 2017-01-30 15:01
Thanks for the quick fix, @bfirsh! You are awesome! (and sorry for the dupe!)
